; PlatformIO Project Configuration File
; Rename this file to `platformio.ini` and fill in your credentials.

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

build_unflags =
  -std=gnu++11

build_flags =
  -D USER_SETUP_LOADED=1
  -include include/TFT_eSPI_Setup.h
  -std=gnu++17

  ; WiFi credentials
  -D WIFI_SSID=\"YourWiFiSSID\"
  -D WIFI_PASS=\"YourWiFiPassword\"

  ; Nightscout (next milestone)
  -D NIGHTSCOUT_URL=\"https://your-nightscout-site\"
  -D NIGHTSCOUT_TOKEN=\"your_api_token\"

lib_deps =
  bodmer/TFT_eSPI
  paulstoffregen/XPT2046_Touchscreen
  SPI
  bblanchon/ArduinoJson @ ^7

board_build.filesystem = littlefs
monitor_dtr = 0
monitor_rts = 0
monitor_filters = time

