; PlatformIO Project Configuration File
; Rename this file to `platformio.ini` and fill in your credentials.

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags =
  -D USER_SETUP_LOADED=1
  -include include/TFT_eSPI_Setup.h
  -std=gnu++17

  ; WiFi credentials
  -DWIFI_SSID=\"YourWiFiSSID\"
  -DWIFI_PASS=\"YourWiFiPassword\"

  ; Nightscout (next milestone)
  -DNIGHTSCOUT_URL=\"https://your-nightscout-site\"
  -DNIGHTSCOUT_TOKEN=\"your_api_token\"

lib_deps =
  bodmer/TFT_eSPI
  paulstoffregen/XPT2046_Touchscreen
  SPI

board_build.filesystem = littlefs
monitor_dtr = 0
monitor_rts = 0
